// <auto-generated />
using System;
using LiveChat.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LiveChat.API.Migrations
{
    [DbContext(typeof(ChatEntities))]
    [Migration("20231227095159_authTable")]
    partial class authTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LiveChat.API.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("LiveChat.API.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachmentUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSent")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MessageDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MessageType")
                        .HasColumnType("int");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AttachmentUrl = "http://queenie.name",
                            Content = "Beatae veniam magni iusto voluptatem provident incidunt saepe aut non.",
                            IsDeleted = false,
                            IsRead = false,
                            IsSent = true,
                            MessageDate = new DateTime(2023, 12, 27, 6, 3, 15, 253, DateTimeKind.Local).AddTicks(6119),
                            MessageType = 0,
                            ReceiverId = 7,
                            SenderId = 7
                        },
                        new
                        {
                            Id = 2,
                            AttachmentUrl = "http://jerald.name",
                            Content = "Aut quos dolorem illo qui.",
                            IsDeleted = false,
                            IsRead = true,
                            IsSent = false,
                            MessageDate = new DateTime(2023, 12, 26, 23, 1, 17, 771, DateTimeKind.Local).AddTicks(3903),
                            MessageType = 0,
                            ReceiverId = 1,
                            SenderId = 7
                        },
                        new
                        {
                            Id = 3,
                            AttachmentUrl = "http://jace.name",
                            Content = "Ut mollitia dolores dolor fugiat nobis sint.",
                            IsDeleted = false,
                            IsRead = true,
                            IsSent = true,
                            MessageDate = new DateTime(2023, 12, 26, 20, 58, 0, 73, DateTimeKind.Local).AddTicks(7285),
                            MessageType = 1,
                            ReceiverId = 7,
                            SenderId = 7
                        },
                        new
                        {
                            Id = 4,
                            AttachmentUrl = "http://lesley.biz",
                            Content = "Odit autem nemo eum et repellat quo.",
                            IsDeleted = true,
                            IsRead = true,
                            IsSent = false,
                            MessageDate = new DateTime(2023, 12, 26, 14, 56, 28, 872, DateTimeKind.Local).AddTicks(3715),
                            MessageType = 1,
                            ReceiverId = 4,
                            SenderId = 2
                        },
                        new
                        {
                            Id = 5,
                            AttachmentUrl = "http://loren.org",
                            Content = "Ut et sed nostrum aut sed numquam.",
                            IsDeleted = true,
                            IsRead = true,
                            IsSent = false,
                            MessageDate = new DateTime(2023, 12, 27, 7, 36, 52, 646, DateTimeKind.Local).AddTicks(7040),
                            MessageType = 3,
                            ReceiverId = 6,
                            SenderId = 6
                        },
                        new
                        {
                            Id = 6,
                            AttachmentUrl = "https://leland.net",
                            Content = "Nemo rerum ut eos et.",
                            IsDeleted = true,
                            IsRead = true,
                            IsSent = false,
                            MessageDate = new DateTime(2023, 12, 26, 12, 46, 24, 338, DateTimeKind.Local).AddTicks(1025),
                            MessageType = 3,
                            ReceiverId = 3,
                            SenderId = 3
                        },
                        new
                        {
                            Id = 7,
                            AttachmentUrl = "https://clemmie.com",
                            Content = "Sed quibusdam reiciendis illum illum aut dolorem qui omnis.",
                            IsDeleted = true,
                            IsRead = true,
                            IsSent = false,
                            MessageDate = new DateTime(2023, 12, 27, 1, 28, 16, 572, DateTimeKind.Local).AddTicks(5040),
                            MessageType = 2,
                            ReceiverId = 9,
                            SenderId = 2
                        },
                        new
                        {
                            Id = 8,
                            AttachmentUrl = "http://elliott.net",
                            Content = "Fuga ea quibusdam sunt veritatis et.",
                            IsDeleted = true,
                            IsRead = false,
                            IsSent = false,
                            MessageDate = new DateTime(2023, 12, 27, 3, 53, 54, 30, DateTimeKind.Local).AddTicks(6551),
                            MessageType = 3,
                            ReceiverId = 1,
                            SenderId = 8
                        },
                        new
                        {
                            Id = 9,
                            AttachmentUrl = "https://jules.com",
                            Content = "Omnis odio sed quisquam occaecati officia harum.",
                            IsDeleted = false,
                            IsRead = false,
                            IsSent = false,
                            MessageDate = new DateTime(2023, 12, 26, 20, 5, 48, 474, DateTimeKind.Local).AddTicks(9202),
                            MessageType = 2,
                            ReceiverId = 9,
                            SenderId = 4
                        },
                        new
                        {
                            Id = 10,
                            AttachmentUrl = "https://winfield.com",
                            Content = "Quo repellat voluptate possimus.",
                            IsDeleted = false,
                            IsRead = false,
                            IsSent = false,
                            MessageDate = new DateTime(2023, 12, 27, 7, 54, 4, 654, DateTimeKind.Local).AddTicks(9863),
                            MessageType = 2,
                            ReceiverId = 2,
                            SenderId = 8
                        },
                        new
                        {
                            Id = 11,
                            AttachmentUrl = "http://taya.biz",
                            Content = "Cupiditate hic nihil.",
                            IsDeleted = false,
                            IsRead = true,
                            IsSent = false,
                            MessageDate = new DateTime(2023, 12, 26, 19, 28, 53, 60, DateTimeKind.Local).AddTicks(7165),
                            MessageType = 3,
                            ReceiverId = 10,
                            SenderId = 4
                        },
                        new
                        {
                            Id = 12,
                            AttachmentUrl = "http://aileen.biz",
                            Content = "Quidem omnis molestiae.",
                            IsDeleted = false,
                            IsRead = true,
                            IsSent = true,
                            MessageDate = new DateTime(2023, 12, 26, 13, 25, 13, 131, DateTimeKind.Local).AddTicks(8790),
                            MessageType = 1,
                            ReceiverId = 7,
                            SenderId = 1
                        },
                        new
                        {
                            Id = 13,
                            AttachmentUrl = "https://rod.info",
                            Content = "Est expedita aliquam ipsa possimus praesentium alias explicabo.",
                            IsDeleted = false,
                            IsRead = true,
                            IsSent = true,
                            MessageDate = new DateTime(2023, 12, 26, 12, 13, 41, 535, DateTimeKind.Local).AddTicks(61),
                            MessageType = 2,
                            ReceiverId = 4,
                            SenderId = 3
                        },
                        new
                        {
                            Id = 14,
                            AttachmentUrl = "http://baylee.name",
                            Content = "Fugiat ut modi architecto expedita aperiam adipisci consequatur autem.",
                            IsDeleted = true,
                            IsRead = true,
                            IsSent = false,
                            MessageDate = new DateTime(2023, 12, 26, 13, 30, 37, 130, DateTimeKind.Local).AddTicks(2987),
                            MessageType = 1,
                            ReceiverId = 9,
                            SenderId = 10
                        },
                        new
                        {
                            Id = 15,
                            AttachmentUrl = "http://alf.biz",
                            Content = "Dignissimos quae perspiciatis omnis incidunt omnis fuga.",
                            IsDeleted = true,
                            IsRead = false,
                            IsSent = true,
                            MessageDate = new DateTime(2023, 12, 27, 9, 15, 0, 821, DateTimeKind.Local).AddTicks(3693),
                            MessageType = 3,
                            ReceiverId = 5,
                            SenderId = 5
                        },
                        new
                        {
                            Id = 16,
                            AttachmentUrl = "http://dario.name",
                            Content = "Mollitia consequatur natus qui et neque natus.",
                            IsDeleted = true,
                            IsRead = false,
                            IsSent = false,
                            MessageDate = new DateTime(2023, 12, 27, 1, 14, 36, 428, DateTimeKind.Local).AddTicks(3618),
                            MessageType = 1,
                            ReceiverId = 4,
                            SenderId = 8
                        },
                        new
                        {
                            Id = 17,
                            AttachmentUrl = "https://ashlynn.net",
                            Content = "Eligendi ducimus nulla debitis velit dicta maxime porro qui.",
                            IsDeleted = true,
                            IsRead = true,
                            IsSent = false,
                            MessageDate = new DateTime(2023, 12, 27, 1, 46, 0, 442, DateTimeKind.Local).AddTicks(9409),
                            MessageType = 1,
                            ReceiverId = 1,
                            SenderId = 9
                        },
                        new
                        {
                            Id = 18,
                            AttachmentUrl = "https://wilbert.net",
                            Content = "Quam vel eius temporibus corporis doloremque voluptatem recusandae molestiae et.",
                            IsDeleted = true,
                            IsRead = false,
                            IsSent = true,
                            MessageDate = new DateTime(2023, 12, 26, 21, 45, 21, 961, DateTimeKind.Local).AddTicks(2098),
                            MessageType = 2,
                            ReceiverId = 5,
                            SenderId = 6
                        },
                        new
                        {
                            Id = 19,
                            AttachmentUrl = "http://frida.biz",
                            Content = "Repudiandae impedit eos modi alias recusandae dolorem ut.",
                            IsDeleted = true,
                            IsRead = false,
                            IsSent = false,
                            MessageDate = new DateTime(2023, 12, 26, 22, 35, 18, 466, DateTimeKind.Local).AddTicks(1885),
                            MessageType = 0,
                            ReceiverId = 6,
                            SenderId = 1
                        },
                        new
                        {
                            Id = 20,
                            AttachmentUrl = "https://lula.biz",
                            Content = "Assumenda consequatur quis perspiciatis fugiat a.",
                            IsDeleted = false,
                            IsRead = false,
                            IsSent = true,
                            MessageDate = new DateTime(2023, 12, 26, 21, 6, 41, 116, DateTimeKind.Local).AddTicks(6802),
                            MessageType = 2,
                            ReceiverId = 6,
                            SenderId = 3
                        });
                });

            modelBuilder.Entity("LiveChat.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UserType");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Justin.Konopelski64@yahoo.com",
                            ImageUrl = "https://picsum.photos/640/480/?image=348",
                            Name = "Justin Konopelski",
                            Password = "sk41HzFizN",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Zachary_Howe77@yahoo.com",
                            ImageUrl = "https://picsum.photos/640/480/?image=1078",
                            Name = "Zachary Howe",
                            Password = "6U65Y1WAR0",
                            Role = "User"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Dan.Shields@hotmail.com",
                            ImageUrl = "https://picsum.photos/640/480/?image=523",
                            Name = "Dan Shields",
                            Password = "yBwGanBPtC",
                            Role = "User"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Jeremiah.Gislason@gmail.com",
                            ImageUrl = "https://picsum.photos/640/480/?image=166",
                            Name = "Jeremiah Gislason",
                            Password = "O4a2SPEVMk",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 5,
                            Email = "Mitchell85@gmail.com",
                            ImageUrl = "https://picsum.photos/640/480/?image=575",
                            Name = "Mitchell Parker",
                            Password = "Le9MWKvg3a",
                            Role = "User"
                        },
                        new
                        {
                            Id = 6,
                            Email = "Shari47@gmail.com",
                            ImageUrl = "https://picsum.photos/640/480/?image=491",
                            Name = "Shari Morar",
                            Password = "bdvKpioDAY",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 7,
                            Email = "Victoria.Rath37@gmail.com",
                            ImageUrl = "https://picsum.photos/640/480/?image=776",
                            Name = "Victoria Rath",
                            Password = "ygYCezOcEe",
                            Role = "User"
                        },
                        new
                        {
                            Id = 8,
                            Email = "Calvin_Anderson@yahoo.com",
                            ImageUrl = "https://picsum.photos/640/480/?image=281",
                            Name = "Calvin Anderson",
                            Password = "bKQbjLiZka",
                            Role = "User"
                        },
                        new
                        {
                            Id = 9,
                            Email = "Rudolph.McKenzie35@hotmail.com",
                            ImageUrl = "https://picsum.photos/640/480/?image=543",
                            Name = "Rudolph McKenzie",
                            Password = "VNHZzd1MfZ",
                            Role = "User"
                        },
                        new
                        {
                            Id = 10,
                            Email = "Opal_Boehm62@yahoo.com",
                            ImageUrl = "https://picsum.photos/640/480/?image=363",
                            Name = "Opal Boehm",
                            Password = "_dkeqMsa8V",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("LiveChat.API.Models.UserConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConnectionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserConnections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConnectionId = "50f0bc8b-099c-e61a-5f56-c571a1badfb4",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            ConnectionId = "f31ce4e6-405b-a884-2daa-99281286bbb7",
                            UserId = 9
                        },
                        new
                        {
                            Id = 3,
                            ConnectionId = "5592dc29-6810-1bfe-1c1f-a97be8cebda0",
                            UserId = 6
                        },
                        new
                        {
                            Id = 4,
                            ConnectionId = "d7179e82-7b30-a76c-6e5e-81be4dcf0aba",
                            UserId = 8
                        },
                        new
                        {
                            Id = 5,
                            ConnectionId = "1c220390-7cd5-d81e-3e20-da2d44dbdb88",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LiveChat.API.Models.Message", b =>
                {
                    b.HasOne("LiveChat.API.Models.User", "Receiver")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LiveChat.API.Models.User", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("LiveChat.API.Models.UserConnection", b =>
                {
                    b.HasOne("LiveChat.API.Models.User", "User")
                        .WithMany("UserConnections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LiveChat.API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LiveChat.API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LiveChat.API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LiveChat.API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LiveChat.API.Models.User", b =>
                {
                    b.Navigation("ReceivedMessages");

                    b.Navigation("SentMessages");

                    b.Navigation("UserConnections");
                });
#pragma warning restore 612, 618
        }
    }
}
